coverage:
  precision: 0
  round: down
  status:
    project:
      default:
       if_not_found: success
    patch:
      default:
        enabled: no
        threshold: 30
        if_not_found: success
comment: false
